name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan your-server-ip >> ~/.ssh/known_hosts

      - name: Deploy Application
        run: |
          ssh tukkie@52.35.34.186 <<EOF
            cd /var/www/fastapi-book-project
            git pull origin main
            source /var/www/fastapi-book-project/venv/bin/activate
            pip install -r requirements.txt
            systemctl restart your-fastapi-service
          EOF
